# Random Module :-

# Python has a built-in module that you can use to make random numbers.

import random

x = random.randint(1,10)        # randint() - Returns a random number between the given range
print(x)

list=["Stone","Paper","Scissor"]
print(random.choice(list))      # choice() - Returns a random element from the given sequence


# For know more about this visit here :- https://www.w3schools.com/python/module_random.asp