# Math Functions -
import math

x = min(5, 10, 25)
y = max(5, 10, 25)

print(x)
print(y)

# abs() :-  returns the absolute (positive) value 
print(abs(-234))

# pow(x, y) :- returns the value of x to the power of y.
print(pow(12,2))

# math.sqrt() :- returns the square root of a number.
print(math.sqrt(64))

# math.pi :- returns the value of PI (3.14...).
print(math.pi)

# math.ceil() :- rounds a number upwards to its nearest integer
print(math.ceil(7.4))

# math.floor() :- rounds a number downwards to its nearest integer
print(math.floor(7.4))