x=15
y=2

print(x+y)  # Addition
print(x-y)  # Subtraction
print(x*y)  # Multiplication
print(x/y)  # Division
print(x//y) # Floor division (Round figure)
print(x%y)  # Modulus (Remainder)
print(x**y) # Exponentiation (15*15)
print(x==y) # Equal	
print(x!=y) # Not equal
print(x>y)  # Greater than
print(x<y)  # Less than	
print(x>=y) # Greater than or equal to	
print(x<=y) # Less than or equal to




